### ISSUE TITLE
Suggestion: consistent numpy documentation style

### ISSUE THREAD

**Issue by x94carbone** [ziatdinovmax/pyroVED#27]
See [here](https://numpydoc.readthedocs.io/en/latest/format.html). I prefer this style personally and it definitely is just a personal choice, but if there are no objections this is how I'll start documenting!

**Comment by ziatdinovmax** [comment]
It's a good style. I don't mind as long as we are consistent (i.e. we don't have a situation where one part of the package uses NumPy style and another one uses Google style).

**Comment by x94carbone** [comment]
See #32 but long story short no I haven't tried to build the docs yet.

**Comment by x94carbone** [comment]
I'll close this for now- we can probably just use your style of documentation plus the auto-docstring generation. No need to complicate things too much for now!
