### ISSUE TITLE
Suggestion: use e.g. `with warnings.catch_warnings()` in favor of module-level warnings suppression

### ISSUE THREAD

**Issue by x94carbone** [ziatdinovmax/pyroVED#29]
https://github.com/ziatdinovmax/pyroVED/blob/185404796d00a2efe3063d6ab84b002496b7befd/pyroved/nets/conv.py#L20

I'd recommend against module-level warnings suppression in favor of

```python3
with warnings.catch_warnings():
    warnings.simplefilter('ignore')
```

at the precise spot where the warnings are thrown.

Thoughts?

**Comment by ziatdinovmax** [comment]
Yes, this would be a more proper way of doing this. I think here we are suppressing the annoying warning about the align_corners from torch.nn.functional.interpolate.

**Comment by x94carbone** [comment]
Yeah this is definitely more nitpicky an issue for sure... I have had my experiences with a crazy number of warnings from `nn.functional` too. If at some point I can pin down exactly where the errors come from (and ensure I don't miss any), I will make this change. For now I'd say this is low priority. After all, it's only suppressing warnings, not errors, which by definition shouldn't really impact the code.
