### ISSUE TITLE
Suggestion: implement mypy type checking

### ISSUE THREAD

**Issue by x94carbone** [ziatdinovmax/pyroVED#33]
While it is a **huge** pain to implement when using custom libraries, e.g. `torch`, since everything is typed in the code anyway, it might be worthwhile to add a proper `mypy` type check into the CI pipeline. That said, I really am no expert on using stubs so it could be a challenge/time consuming.

Edit: actually it doesn't look *too* bad: https://realpython.com/python-type-checking/#adding-stubs

**Comment by ziatdinovmax** [comment]
I haven't had my experience with ```mypy``` but it does look nice/useful. I'll see if I can add this to the 'workflows'.

**Comment by x94carbone** [comment]
Ok sounds good. It's as simple as running `mypy pyroved` from the project home directory, but getting stubs to work is an entirely different story. Not entirely necessary, but type checking is extremely powerful when implemented properly.

**Comment by x94carbone** [comment]
I think this is probably something we shouldn't worry about right now. It's also a huge pain to use stubs and whatnot. Closing for now.
