### ISSUE TITLE
Refactor the models classes due to repetition

### ISSUE THREAD

**Issue by x94carbone** [ziatdinovmax/pyroVED#34]
There appears to be quite a bit of repetition in the classes in `models.py`, especially in e.g. the `__init__`. I'd suggest refactoring, and moving a lot of the shared code into the base class (and then adding documentation to the base class, of course).

**Comment by ziatdinovmax** [comment]
That's true and I'm aware of that but at this point I'm not yet sure what other models I'm going to add and how they would relate to the existing ones (there are dozens of cool VAE/VED extensions that could be tried but given the lack of time a lot will depend on the specific research needs) so I'm bit hesitant to do the refactoring now. In some sense, I'm waiting for "the bigger picture" to emerge in my head. I think that some repetition is acceptable at the early stages of any project.

**Comment by x94carbone** [comment]
Sure, not a problem. Something to keep in mind for the future; for now let's close it.
